### ISSUE TITLE
Not Changing WebView

### ISSUE THREAD

**Issue by TombolaShepless** [Im-Kevin/cordova.plugins.X5WebView#2]
I have installed the plugin as instructed, however my user agent is returning:

`Mozilla/5.0 (Linux; Android 6.0; Samsung Galaxy S6 - 6.0.0 - API 23 - 1440x2560 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36`

I have unzipped the APK file and the `tbs_sdk_thirdapp_v3.1.0.1034_43100_sharewithdownload_obfs_20170301_182143.jar` file is not in `lib` could this be the problem?

Not sure how to get this working?

I'm using:

- cordova-android: 6.2.1
- cordova: 6.5.0

**Comment by Im-Kevin** [comment]
Sorry, I can't speak English

你可以看看  platforms/android/libs 是否有tbs_sdk_thirdapp_v3.1.0.1034_43100_sharewithdownload_obfs_20170301_182143.jar
如果有,你可以尝试删除你手机上的APP,然后运行 
`cordova clean`
然后重新试一下

**Comment by Im-Kevin** [comment]
还有你的手机是否存在 QQ WeChat 等腾讯的App

**Comment by TombolaShepless** [comment]
Ah - you need App QQ WeChat installed on same device?

啊 - 你需要安装在同一台设备上的App QQ WeChat吗？(Google Translate - sorry)

**Comment by Im-Kevin** [comment]
因为这个是腾讯通过旗下产品自带的浏览器内核运行的,所以他的大小只有200多KB,因为中国QQ WeChat很普遍,所以没有这个问题,如果你那边没有这么普及,我建议你使用
[cordova-android-crosswalk](https://github.com/tylerbuchea/cordova-android-crosswalk)

Because this is Tencent through its own product comes with the browser kernel to run, so his size is only 200 KB, because China QQ WeChat is very common, so there is no such problem, if you are not so popular, I suggest you use (Google Translate - sorry)
[cordova-android-crosswalk](https://github.com/tylerbuchea/cordova-android-crosswalk)

**Comment by TombolaShepless** [comment]
谢谢

**Comment by Im-Kevin** [comment]
you are welcome
